### ISSUE TITLE
Package Versions Issue

### ISSUE THREAD

**Issue by xador70** [cedricgsh/ISDNet#11]
Hi, I'm trying your code. I'm new to MMCV library. I'm having a bit of difficulty with the package versions. Can you share the package versions that you used in this paper?

I tried with the latest versions and (MMSeg 0.16 and MMCV 1.3.7) but I still get an error every time. And also, I'm working on Windows, did you run this project on which system? 

Thank you for your time.

**Comment by cedricgsh** [comment]
Thanks for your attention. We use the MMseg 0.16.0 and MMCV 1.3.5 and run this code on Ubuntu.

**Comment by songcv** [comment]
> Thanks for your attention. We use the MMseg 0.16.0 and MMCV 1.3.5 and run this code on Ubuntu.

2023-05-26 14:49:21,645 - mmseg - INFO - workflow: [('train', 1)], max: 80000 iters
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1595629411241/work/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "tools/train.py", line 217, in <module>
    main()
  File "tools/train.py", line 204, in main
    train_segmentor(
  File "/root/autodl-tmp/ISDNet/mmseg/apis/train.py", line 127, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/root/miniconda3/envs/isdnet/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/root/miniconda3/envs/isdnet/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/root/miniconda3/envs/isdnet/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/root/autodl-tmp/ISDNet/mmseg/models/segmentors/base.py", line 137, in train_step
    losses = self(**data_batch)
  File "/root/miniconda3/envs/isdnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/isdnet/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/root/autodl-tmp/ISDNet/mmseg/models/segmentors/base.py", line 107, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/root/autodl-tmp/ISDNet/mmseg/models/segmentors/encoder_decoder_refine.py", line 132, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_refine, img_metas, gt_semantic_seg)
  File "/root/autodl-tmp/ISDNet/mmseg/models/segmentors/encoder_decoder_refine.py", line 152, in _decode_head_forward_train
    loss_refine, *loss_contrsative_list = self.refine_head.forward_train(img, prev_features, img_metas, gt_semantic_seg, self.train_cfg)
  File "/root/autodl-tmp/ISDNet/mmseg/models/decode_heads/isdhead.py", line 279, in forward_train
    seg_logits, seg_logits_aux16, seg_logits_aux8, losses_recon, losses_fa = self.forward(inputs, prev_output)
  File "/root/autodl-tmp/ISDNet/mmseg/models/decode_heads/isdhead.py", line 231, in forward
    high_residual_input = torch.cat([high_residual_1, high_residual_2], dim=1)
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1595629411241/work/aten/src/THC/THCCachingHostAllocator.cpp:278
Aborted (core dumped)





raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 128, 1, 1])



1.7.1>=mmcv>=1.3.7
